name: Valgrind
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
  push:
  pull_request:
jobs:

  valgrind:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install package
      run: |
        sudo apt-get -y install valgrind
    - name: Build
      uses: github/codeql-action/autobuild@v2
        
    - name: Test
      run: |
        valgrind --tool=memcheck --leak-check=full --show-leaks-kind=yes
        
